//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_AutomatizacionCGI.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleRespuesta
    {
        public int ID_DetalleRespuesta { get; set; }
        public int ID_Encuesta { get; set; }
        public int ID_Pregunta { get; set; }
        public int ID_Aceso { get; set; }
        public int ID_Respuesta { get; set; }
    
        public virtual Acceso Acceso { get; set; }
        public virtual Encuesta Encuesta { get; set; }
        public virtual Pregunta Pregunta { get; set; }
    }
}
