//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_AutomatizacionCGI.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pad()
        {
            this.Asistencia = new HashSet<Asistencia>();
        }
    
        public int ID_Pad { get; set; }
        public int ID_Curso { get; set; }
        public string Sala { get; set; }
        public string Sala_Coffe { get; set; }
        public string Hora_Inicio { get; set; }
        public string Hora_Termino { get; set; }
        public System.DateTime Fecha { get; set; }
        public int ID_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asistencia> Asistencia { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
