//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_AutomatizacionCGI.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta
    {
        public int ID_Respuesta { get; set; }
        public Nullable<int> ID_Pregunta { get; set; }
        public string Detalle { get; set; }
    
        public virtual Pregunta Pregunta { get; set; }
    }
}
