//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_AutomatizacionCGI.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuestas
    {
        public int ID_Respuesta { get; set; }
        public int ID_Encuesta { get; set; }
        public string ID_Pregunta { get; set; }
        public string Respuesta { get; set; }
        public int ID_Curso { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Encuesta Encuesta { get; set; }
        public virtual Pregunta Pregunta { get; set; }
    }
}
